### PR TITLE
mpx primer additions

### PR DESCRIPTION
**Pull request by tives82**
Erin, I thought I'd just do a PR to add the mpx primer profile to save you a little time rather than sending you the files by other means but please change anything I've done however you'd like. I've selected to allow edits.

### CODE REVIEW

**Comment by erinyoung** [comment]
I think this looks okay, but I can't change the default MPX to ON568298.1
- The community has asked the default to be NC_063383.1
- NextClade uses NC_063383.1
- The gff3 file for ON568298.1 is devoid of information

**Comment by erinyoung** [comment]
I think we need to adjust the primer bedfile to NC_063383.1 coordinates

**Comment by fanninpm** [comment]
@erinyoung Do you instead want the primers from [this protocol by Chen et al?](https://www.protocols.io/view/monkeypox-virus-multiplexed-pcr-amplicon-sequencin-5qpvob1nbl4o)

**Comment by erinyoung** [comment]
@fanninpm the primalseq primers would be good to add, too. 

primalseq uses MT903345 for their reference.

```
MT903345	356	378	MPXV_1_LEFT	1	+
MT903345	2395	2417	MPXV_1_RIGHT	1	-
MT903345	1439	1461	MPXV_2_LEFT	2	+
MT903345	3353	3375	MPXV_2_RIGHT	2	-
MT903345	2606	2628	MPXV_3_LEFT	1	+
MT903345	4593	4615	MPXV_3_RIGHT	1	-
MT903345	3990	4012	MPXV_4_LEFT	2	+
MT903345	5584	5607	MPXV_4_RIGHT	2	-
MT903345	4991	5013	MPXV_5_LEFT	1	+
MT903345	7027	7049	MPXV_5_RIGHT	1	-
MT903345	6134	6156	MPXV_6_LEFT	2	+
MT903345	8202	8224	MPXV_6_RIGHT	2	-
MT903345	7417	7439	MPXV_7_LEFT	1	+
MT903345	9405	9427	MPXV_7_RIGHT	1	-
MT903345	8858	8880	MPXV_8_LEFT	2	+
MT903345	10646	10668	MPXV_8_RIGHT	2	-
MT903345	9767	9789	MPXV_9_LEFT	1	+
MT903345	11731	11753	MPXV_9_RIGHT	1	-
MT903345	10729	10751	MPXV_10_LEFT	2	+
MT903345	12880	12902	MPXV_10_RIGHT	2	-
MT903345	12290	12312	MPXV_11_LEFT	1	+
MT903345	14020	14042	MPXV_11_RIGHT	1	-
MT903345	13079	13101	MPXV_12_LEFT	2	+
MT903345	15347	15369	MPXV_12_RIGHT	2	-
MT903345	14663	14685	MPXV_13_LEFT	1	+
MT903345	16733	16755	MPXV_13_RIGHT	1	-
MT903345	15866	15888	MPXV_14_LEFT	2	+
MT903345	18116	18138	MPXV_14_RIGHT	2	-
MT903345	17282	17304	MPXV_15_LEFT	1	+
MT903345	19262	19284	MPXV_15_RIGHT	1	-
MT903345	18294	18316	MPXV_16_LEFT	2	+
```

**Review by erinyoung — APPROVED** [review]

**Review by erinyoung — APPROVED** [review]

**Pull request merged**
